name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs checkout
      
      - name: Get last commit message
        id: commit-message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
      - name: Check commit message for deploy trigger
        if: "contains(steps.commit-message.outputs.message, '[deploy]')"
        run: echo "Deploying because commit message contains [deploy]"

      - name: Login to Docker Hub
        if: "contains(steps.commit-message.outputs.message, '[deploy]')"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        if: "contains(steps.commit-message.outputs.message, '[deploy]')"
        run: |
          docker build -t bach2690/deepweb:${{ github.sha }} -f Dockerfile .
          docker push bach2690/deepweb:${{ github.sha }}
          docker build -t bach2690/deepnginx:${{ github.sha }} -f nginx/Dockerfile ./nginx
          docker push bach2690/deepnginx:${{ github.sha }}

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/kubeconfig
          echo "KUBECONFIG=$HOME/kubeconfig" >> $GITHUB_ENV

      - name: Update Kubernetes Deployment with New Image
        run: |
          kubectl --kubeconfig=$HOME/kubeconfig set image deployment/deepweb-deployment deepweb=bach2690/deepweb:${{ github.sha }} -n your-namespace
          kubectl --kubeconfig=$HOME/kubeconfig set image deployment/deepnginx-deployment deepnginx=bach2690/deepnginx:${{ github.sha }} -n your-namespace





